version: 2
enable-beta-ecosystems: true

updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"

    - package-ecosystem: "npm"
      directory: "/scripts/bluesky"
      schedule:
          interval: "daily"
      versioning-strategy: increase
      ignore:
          - dependency-name: "tailwindcss"
            versions:
                - "^4.0.0"

    - package-ecosystem: "nuget"
      directory: "/src/test/umbraco"
      schedule:
          interval: "daily"
      versioning-strategy: increase
      
