name: Validate Commits

on: [pull_request]

jobs:
    commitlint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3.5.3
              with:
                  fetch-depth: 0
            - uses: wagoid/commitlint-github-action@v5.4.1
              with:
                  configFile: "./.commitlintrc.yml"
