name: Discord
on:
    release:
        types: [published]

jobs:
    notify:
        runs-on: ubuntu-latest
        steps:
            - name: Notes 📝
              id: notes
              uses: actions/github-script@v6.4.1
              with:
                  result-encoding: string
                  script: |
                      notes = context.payload.release.body

                                // replace all non-supported characters
                                notes = notes.replaceAll('###', '')
                                notes = notes.trim()
                                return notes
                      - name: Changelog 📝
                        uses: sebastianpopp/discord-action@v2.0
                        with:
                            webhook: ${{ secrets.CHANGELOG_WEBHOOK }}
                            message: |
                                📦 ${{ github.event.release.name }}

                                          ${{steps.notes.outputs.result}}

                                          ${{ github.event.release.html_url }}
