name: Markdownlint

on: [pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3.5.3
            - name: Lint files
              uses: articulate/actions-markdownlint@v1.1.0
              with:
                  files: .
                  config: .markdownlint.yaml
