name: Social
on:
    release:
        types: [published]
    workflow_dispatch:

jobs:
    bluesky:
        runs-on: ubuntu-latest
        steps:
            - name: Install Node ⬇️
              uses: actions/setup-node@v4.4.0
              with:
                  node-version: 18
            - name: Checkout code 👋
              uses: actions/setup-node@v4.4.0
            - name: Skyt 🌤️
              working-directory: scripts/bluesky
              env:
                  BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
                  BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
                  OWNER: JanDeDobbeleer
                  REPO: oh-my-posh
              run: |
                  npm install
                  node main.js
